name = "cloudflare-img"
compatibility_date = "2024-09-23"
pages_build_output_dir = "frontend-dist"

[[kv_namespaces]]
binding = "img_url"
id = "5ab18bc47528474e802718472970e9af"

[[r2_buckets]]
binding = "img_r2"
bucket_name = "img"
